package com.alexandru_budau.springboot_server.models;

import jakarta.persistence.*;

@Entity
@Table(name = "the_oscar_awards")
public class OscarAwards {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // autogenerated primary key

    @Column(name = "year_film")      // Use double quotes!
    private int yearFilm;

    @Column(name = "year_ceremony")  // Use double quotes!
    private int yearCeremony;

    @Column(name = "ceremony")       // Use double quotes!
    private int ceremony;

    @Column(name = "category")       // Use double quotes!
    private String category;

    @Column(name = "name")           // Use double quotes!
    private String name;

    @Column(name = "film")           // Use double quotes!
    private String film;

    @Column(name = "winner")         // Use double quotes!
    private boolean winner;

    public OscarAwards() {}

    public OscarAwards(int yearFilm, int yearCeremony, int ceremony, String category, String name, String film, boolean winner) {
        this.yearFilm = yearFilm;
        this.yearCeremony = yearCeremony;
        this.ceremony = ceremony;
        this.category = category;
        this.name = name;
        this.film = film;
        this.winner = winner;
    }

    // Getters and setters
    public Long getId() { return id; }

    public int getYearFilm() { return yearFilm; }
    public void setYearFilm(int yearFilm) { this.yearFilm = yearFilm; }

    public int getYearCeremony() { return yearCeremony; }
    public void setYearCeremony(int yearCeremony) { this.yearCeremony = yearCeremony; }

    public int getCeremony() { return ceremony; }
    public void setCeremony(int ceremony) { this.ceremony = ceremony; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getFilm() { return film; }
    public void setFilm(String film) { this.film = film; }

    public boolean isWinner() { return winner; }
    public void setWinner(boolean winner) { this.winner = winner; }
}